name: build

on:
  push:
    branches:
      - main

env: # Change this if needed
  quarto_file: dl-occupancy-lynx-paper
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  computorticle:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Installing dependencies with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: computo

      - name: Install additional R dependencies
        run: | 
          export LANG=en_US.UTF-8
          conda run -n computo Rscript r-addons.R
 
      - name: Installing quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Rendering with Quarto
        shell: bash -l {0}
        run: |
            mkdir _build
            quarto render ${{ env.quarto_file }}.Rmd
            mv ${{ env.quarto_file }}.html _build/index.html
            mv ${{ env.quarto_file }}.ipynb _build/
            cp environment.yml _build/

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
